# Generated by Django 5.2.8 on 2025-11-12 05:01

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('accounts', '0001_initial'),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
