# Generated by Django 5.2.8 on 2025-11-12 05:09

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('accounts', '0002_user_organization'),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
