# Generated by Django 5.2.7 on 2025-11-08 14:49

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name='denuncia',
            name='protocolo',
            field=models.CharField(db_index=True, default=api.models.ulid_str, editable=False, max_length=26, unique=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
