# Generated by Django 5.2.8 on 2025-11-12 05:00

import uuid
from typing import ClassVar

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('api', '0002_denuncia_protocolo_denuncia_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name='HistoricalDenuncia',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('protocolo', models.CharField(db_index=True, default=api.models.ulid_str, editable=False, max_length=26)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('midia', models.TextField(blank=True, max_length=100, null=True)),
                ('audio', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='em_analise', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical denuncia',
                'verbose_name_plural': 'historical denuncias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
